# Generated by Django 3.1.4 on 2020-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duser', models.CharField(max_length=100)),
                ('dpass', models.CharField(max_length=100)),
            ],
        ),
    ]
