# Generated by Django 3.1.4 on 2020-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gaurds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guser', models.CharField(max_length=100)),
                ('gfname', models.CharField(max_length=100)),
                ('glname', models.CharField(max_length=100)),
                ('gpass', models.CharField(max_length=100)),
            ],
        ),
    ]
