# Generated by Django 3.1.4 on 2020-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaurd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('intime', models.CharField(max_length=100)),
                ('extime', models.CharField(max_length=100)),
            ],
        ),
    ]
